# Generated by Django 5.2.5 on 2026-08-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0026_historicalrevenuebalance'),
        ('vendors', '0024_remove_vendorclientallocation_client_consumed_not_above_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyattempt',
            name='supplier_respondent_id',
            field=models.CharField(blank=True, db_index=True, help_text="Supplier's respondent identifier returned on its configured outcome URL.", max_length=160),
        ),
        migrations.AddField(
            model_name='surveyattempt',
            name='vendor_api_key',
            field=models.ForeignKey(blank=True, help_text='External supplier API key that issued this respondent link.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='vendors.vendorapikey'),
        ),
    ]
