"""Code-owned, page-grouped catalog for function-level permissions.

Every new page component must be registered here. ``manage.py migrate``
synchronizes entries into AccessFunction so they appear in both role and
individual-user permission editors. Default grants are applied only when a
function is first created; later administrator changes are never overwritten.
"""

from django.db import transaction


ALL_ROLES = ("employee", "employees", "team-lead", "tl", "manager", "admin", "super-admin")
TRACKING_ROLES = ("team-lead", "tl", "manager", "admin", "super-admin")
ADMIN_ROLES = ("admin", "super-admin")
SUPER_ADMIN_ROLES = ("super-admin",)


# code, name, page-wise group, description, default system roles
FUNCTION_CATALOG = (
    ("dashboard.view", "View dashboard page and sidebar item", "Dashboard - Page & navigation", "Open the dashboard and display its sidebar navigation item.", SUPER_ADMIN_ROLES),
    ("dashboard.card.hits", "Show Total hits card", "Dashboard - Summary cards", "Display the filtered respondent journey count.", SUPER_ADMIN_ROLES),
    ("dashboard.card.completes", "Show Completes card", "Dashboard - Summary cards", "Display successful survey outcomes.", SUPER_ADMIN_ROLES),
    ("dashboard.card.conversion", "Show Conversion card", "Dashboard - Summary cards", "Display completes divided by total hits.", SUPER_ADMIN_ROLES),
    ("dashboard.card.active_users", "Show Active users card", "Dashboard - Summary cards", "Display users with activity matching the current filters.", SUPER_ADMIN_ROLES),
    ("dashboard.card.average_loi", "Show Average LOI card", "Dashboard - Summary cards", "Display average recorded survey journey duration.", SUPER_ADMIN_ROLES),
    ("dashboard.card.revenue", "Show Revenue card", "Dashboard - Summary cards", "Display completed revenue from immutable hit-time CPI snapshots.", SUPER_ADMIN_ROLES),
    ("dashboard.card.average_cpi", "Show Average CPI card", "Dashboard - Summary cards", "Display average immutable hit-time CPI across completed journeys.", SUPER_ADMIN_ROLES),
    ("dashboard.card.rpc", "Show Revenue per hit card", "Dashboard - Summary cards", "Display visible completed revenue divided by total respondent hits.", SUPER_ADMIN_ROLES),
    ("dashboard.card.ir", "Show IR card", "Dashboard - Summary cards", "Display completes divided by completes plus survey terminations; local pre-screen terminations, quota and security outcomes are excluded.", SUPER_ADMIN_ROLES),
    ("dashboard.chart.performance", "Show Performance graph", "Dashboard - Charts", "Display range-aware traffic, conversion and permitted financial trends from 24 hours through 1 year.", SUPER_ADMIN_ROLES),
    ("dashboard.chart.client_share", "Show Client contribution chart", "Dashboard - Charts", "Display each client's share of filtered completes.", SUPER_ADMIN_ROLES),
    ("dashboard.chart.status", "Show Outcome mix chart", "Dashboard - Charts", "Display initiated, complete, terminated, quota and security outcomes.", SUPER_ADMIN_ROLES),
    ("dashboard.chart.device", "Show Device performance chart", "Dashboard - Charts", "Display completed outcomes by Desktop, Mobile and Tablet.", SUPER_ADMIN_ROLES),
    ("dashboard.chart.top_users", "Show Top performers chart", "Dashboard - Charts", "Display visible users ranked by filtered completes.", SUPER_ADMIN_ROLES),
    ("dashboard.graph.traffic_filters", "Filter Traffic dashboard graph", "Dashboard - Graph filters", "Use an independent client and time-range filter on the Entrants, Completes and Conversion graph.", SUPER_ADMIN_ROLES),
    ("dashboard.graph.finance_filters", "Filter Revenue dashboard graph", "Dashboard - Graph filters", "Use an independent client and time-range filter on the Revenue and RPC graph.", SUPER_ADMIN_ROLES),

    ("projects.view", "View Projects page, sidebar and rows", "Projects - Page & navigation", "Open Projects, display its sidebar item and read project rows through the API.", ALL_ROLES),
    ("projects.filter.search", "Use Search filter", "Projects - Filters", "Search project identifiers and descriptive fields.", ALL_ROLES),
    ("projects.filter.country", "Use Country filter", "Projects - Filters", "Filter projects by one or more countries.", ALL_ROLES),
    ("projects.filter.status", "Use Status filter", "Projects - Filters", "Filter projects by one or more statuses.", ALL_ROLES),
    ("projects.filter.client", "Use Client filter", "Projects - Filters", "Filter projects by one or more clients.", ALL_ROLES),
    ("projects.filter.buyer", "Use Buyer ID filter", "Projects - Filters", "Filter projects by provider buyer/sub-client identifiers.", ALL_ROLES),
    ("projects.filter.survey_type", "Use Survey type filter", "Projects - Filters", "Filter projects by normalized B2B or B2C audience type.", ALL_ROLES),
    ("projects.filter.cpi", "Use CPI range and sorting filter", "Projects - Filters", "Filter projects by CPI range and sort by CPI.", ADMIN_ROLES),
    ("projects.filter.date", "Use Date and time filter", "Projects - Filters", "Filter project created or modified timestamps with combined From and To controls.", ALL_ROLES),
    ("projects.filters.clear", "Clear project filters", "Projects - Filters", "Use the Clear filters action on Projects.", ALL_ROLES),
    ("projects.export", "Export projects workbook", "Projects - Actions", "Download all projects matching the permitted current filters as an Excel workbook.", ALL_ROLES),
    ("survey_details.view", "View survey details", "Projects - Actions", "Open pre-screening and quota details.", ALL_ROLES),
    ("survey_links.copy", "Copy pre-screener links", "Projects - Actions", "Copy internal respondent start links.", ALL_ROLES),
    ("projects.control.page_size", "Change rows per page", "Projects - Page controls", "Change the number of project rows displayed per page.", ALL_ROLES),
    ("projects.control.pagination", "Use pagination", "Projects - Page controls", "Move between pages of project rows.", ALL_ROLES),
    ("projects.column.project_id", "Show Project ID column", "Projects - Table columns", "Display the internal project identifier.", ALL_ROLES),
    ("projects.column.client_name", "Show Client name in Project table", "Projects - Table columns", "Display the client name below Project ID in the desktop table, mobile cards, survey-details drawer and Projects export.", ALL_ROLES + ("external-vendor",)),
    ("projects.column.survey", "Show Survey column", "Projects - Table columns", "Display survey ID, name and client.", ALL_ROLES),
    ("projects.column.market", "Show Market column", "Projects - Table columns", "Display country and language.", ALL_ROLES),
    ("projects.column.completes", "Show Completes column", "Projects - Table columns", "Display completion progress and sample size.", ALL_ROLES),
    ("projects.column.cpi", "Show CPI column", "Projects - Table columns", "Display cost per interview.", ALL_ROLES),
    ("projects.column.loi_ir", "Show LOI / IR column", "Projects - Table columns", "Display interview length and incidence rate.", ALL_ROLES),
    ("projects.column.entry_link", "Show Entry link column", "Projects - Table columns", "Display the internal pre-screener copy action.", ALL_ROLES),
    ("projects.column.modified", "Show Modified column", "Projects - Table columns", "Display source timestamp and survey status.", ALL_ROLES),
    ("projects.column.actions", "Show Actions column", "Projects - Table columns", "Display the survey details action.", ALL_ROLES),

    ("attempts.view", "View Traffic Reports page, sidebar and rows", "Traffic Reports - Page & navigation", "Open Traffic Reports, display its sidebar item and read respondent rows through the API.", TRACKING_ROLES),
    ("studies.filter.search", "Use Search filter", "Traffic Reports - Filters", "Search respondent, survey, user, network and browser data.", TRACKING_ROLES),
    ("studies.filter.branch", "Use Branch filter", "Traffic Reports - Filters", "Filter Traffic Reports by one or more authorized organization branches.", TRACKING_ROLES),
    ("studies.filter.sub_branch", "Use Sub-branch filter", "Traffic Reports - Filters", "Filter Traffic Reports by one or more authorized organization sub-branches.", TRACKING_ROLES),
    ("studies.filter.shift", "Use Shift filter", "Traffic Reports - Filters", "Filter Traffic Reports by one or more authorized organization shifts.", TRACKING_ROLES),
    ("studies.filter.user", "Use User filter", "Traffic Reports - Filters", "Filter Traffic Reports by one or more users.", TRACKING_ROLES),
    ("studies.filter.status", "Use Status filter", "Traffic Reports - Filters", "Filter Traffic Reports by one or more outcomes.", TRACKING_ROLES),
    ("studies.filter.country", "Use Country filter", "Traffic Reports - Filters", "Filter Traffic Reports by one or more survey countries.", TRACKING_ROLES),
    ("studies.filter.client", "Use Client filter", "Traffic Reports - Filters", "Filter Traffic Reports by one or more clients.", TRACKING_ROLES),
    ("studies.filter.buyer", "Use Sub-client / Buyer ID filter", "Traffic Reports - Filters", "Filter Traffic Reports by provider buyer/sub-client identifiers.", TRACKING_ROLES),
    ("studies.filter.project", "Use Project deep-link filter", "Traffic Reports - Filters", "Open Traffic Reports scoped to one Project ID from the Projects table.", TRACKING_ROLES),
    ("studies.filter.date", "Use Date and time filter", "Traffic Reports - Filters", "Filter entry or callback timestamps with combined From and To controls.", TRACKING_ROLES),
    ("studies.filters.clear", "Clear traffic report filters", "Traffic Reports - Filters", "Use the Clear filters action on Traffic Reports.", TRACKING_ROLES),
    ("attempts.export", "Export Traffic Reports workbook", "Traffic Reports - Actions", "Export the agreed respondent audit columns matching permitted filters as an Excel workbook.", ("super-admin",)),
    ("studies.control.page_size", "Change rows per page", "Traffic Reports - Page controls", "Change the number of traffic report rows displayed per page.", TRACKING_ROLES),
    ("studies.control.pagination", "Use pagination", "Traffic Reports - Page controls", "Move between pages of respondent rows.", TRACKING_ROLES),
    ("studies.column.project_id", "Show Project ID column", "Traffic Reports - Table columns", "Display the internal project identifier.", TRACKING_ROLES),
    ("studies.column.survey_id", "Show Survey ID column", "Traffic Reports - Table columns", "Display the upstream survey identifier.", TRACKING_ROLES),
    ("studies.column.country", "Show Country column", "Traffic Reports - Table columns", "Display the survey country captured through the related project.", TRACKING_ROLES),
    ("studies.column.cpi", "Show snapshot CPI column", "Traffic Reports - Table columns", "Display the CPI frozen when the respondent hit the survey.", TRACKING_ROLES),
    ("studies.column.respondent_id", "Show Respondent ID column", "Traffic Reports - Table columns", "Display the internal respondent RID.", TRACKING_ROLES),
    ("studies.column.user", "Show Name column", "Traffic Reports - Table columns", "Display respondent user name and email.", TRACKING_ROLES),
    ("studies.column.device", "Show Device column", "Traffic Reports - Table columns", "Display the captured device type.", TRACKING_ROLES),
    ("studies.column.ip", "Show IP address column", "Traffic Reports - Table columns", "Display captured entry and exit network IPs.", TRACKING_ROLES),
    ("studies.column.loi", "Show LOI column", "Traffic Reports - Table columns", "Display measured survey duration.", TRACKING_ROLES),
    ("studies.column.status", "Show Status column", "Traffic Reports - Table columns", "Display the normalized survey outcome.", TRACKING_ROLES),
    ("studies.column.start", "Show Start column", "Traffic Reports - Table columns", "Display the survey start timestamp.", TRACKING_ROLES),
    ("studies.column.end", "Show End column", "Traffic Reports - Table columns", "Display the callback or current end timestamp.", TRACKING_ROLES),
    ("studies.card.total", "Show Total hits card", "Traffic Reports - Summary cards", "Display the filtered traffic report hit total.", TRACKING_ROLES),
    ("studies.card.initiated", "Show Initiated card", "Traffic Reports - Summary cards", "Display initiated traffic report journeys.", TRACKING_ROLES),
    ("studies.card.completed", "Show Completed card", "Traffic Reports - Summary cards", "Display completed traffic report journeys.", TRACKING_ROLES),
    ("studies.card.terminated", "Show Terminated card", "Traffic Reports - Summary cards", "Display terminated traffic report journeys.", TRACKING_ROLES),
    ("studies.card.quota", "Show Quota card", "Traffic Reports - Summary cards", "Display over-quota traffic report journeys.", TRACKING_ROLES),
    ("studies.card.security", "Show Security card", "Traffic Reports - Summary cards", "Display quality and security terminations.", TRACKING_ROLES),
    ("studies.card.conversion", "Show Conversion card", "Traffic Reports - Summary cards", "Display completed-to-hit conversion.", TRACKING_ROLES),
    ("studies.card.desktop", "Show Desktop completes card", "Traffic Reports - Summary cards", "Display completed Desktop journeys.", TRACKING_ROLES),
    ("studies.card.mobile", "Show Mobile completes card", "Traffic Reports - Summary cards", "Display completed Mobile journeys.", TRACKING_ROLES),
    ("studies.card.tablet", "Show Tablet completes card", "Traffic Reports - Summary cards", "Display completed Tablet journeys.", TRACKING_ROLES),
    ("studies.card.revenue", "Show Total Revenue card", "Traffic Reports - Summary cards", "Display completed revenue using the CPI snapshot captured at hit time.", ADMIN_ROLES),
    ("studies.card.ir", "Show IR card", "Traffic Reports - Summary cards", "Display completes divided by completes plus actual survey terminations.", TRACKING_ROLES),

    ("prescreener_data.view", "View Panelist Data page and sidebar", "Panelist Data - Page & navigation", "Open the isolated panelist profile vault.", ADMIN_ROLES),
    ("prescreener_data.filter.search", "Search UID", "Panelist Data - Filters", "Search panelist profiles by internal UID.", ADMIN_ROLES),
    ("prescreener_data.filter.country", "Filter by country", "Panelist Data - Filters", "Filter panelist profiles by captured country.", ADMIN_ROLES),
    ("prescreener_data.filter.language", "Filter by language", "Panelist Data - Filters", "Filter panelist profiles by captured survey language.", ADMIN_ROLES),
    ("prescreener_data.filter.age_group", "Filter by age group", "Panelist Data - Filters", "Filter profiles by normalized respondent age group.", ADMIN_ROLES),
    ("prescreener_data.filter.gender", "Filter by gender", "Panelist Data - Filters", "Filter profiles by normalized respondent gender.", ADMIN_ROLES),
    ("prescreener_data.filters.clear", "Clear Panelist Data filters", "Panelist Data - Filters", "Clear all panelist profile filters.", ADMIN_ROLES),
    ("prescreener_data.export", "Export Panelist Data workbook", "Panelist Data - Actions", "Export every filtered profile and its linked details as a formatted Excel workbook.", ADMIN_ROLES),
    ("prescreener_data.control.pagination", "Use profile pagination", "Panelist Data - Page controls", "Move between pages of panelist profiles.", ADMIN_ROLES),
    ("prescreener_data.column.uid", "Show UID column", "Panelist Data - Table columns", "Display the immutable panelist UID.", ADMIN_ROLES),
    ("prescreener_data.column.market", "Show country and language column", "Panelist Data - Table columns", "Display the captured country and language snapshot.", ADMIN_ROLES),
    ("prescreener_data.column.profile", "Show Profile Specs column", "Panelist Data - Table columns", "Display normalized age, gender, ethnicity and postal profile values.", ADMIN_ROLES),
    ("prescreener_data.column.answers", "Show Profile Information", "Panelist Data - Table columns", "Open exact profile questions and captured answers.", ADMIN_ROLES),
    ("prescreener_data.column.usage_count", "Show Visits column", "Panelist Data - Table columns", "Display the original visit plus policy-approved profile reuses for this UID.", ADMIN_ROLES),
    ("prescreener_data.column.captured", "Show Registered at column", "Panelist Data - Table columns", "Display when the panelist profile was registered.", ADMIN_ROLES),

    ("termination_reasons.view", "View Term Reports page and sidebar", "Term Reports - Page & navigation", "Open the administrator-only provider outcome lookup page and display its sidebar item.", ADMIN_ROLES),
    ("termination_reasons.filter.rid", "Use Term Reports search", "Term Reports - Filters", "Search final unsuccessful attempts by RID, PID, UID, project, survey, buyer, user or network address.", ADMIN_ROLES),
    ("termination_reasons.filter.branch", "Filter by branch", "Term Reports - Filters", "Filter unsuccessful outcomes by one or more organization branches.", ADMIN_ROLES),
    ("termination_reasons.filter.sub_branch", "Filter by sub-branch", "Term Reports - Filters", "Filter unsuccessful outcomes by one or more organization sub-branches.", ADMIN_ROLES),
    ("termination_reasons.filter.shift", "Filter by shift", "Term Reports - Filters", "Filter unsuccessful outcomes by one or more organization shifts.", ADMIN_ROLES),
    ("termination_reasons.filter.user", "Filter by user", "Term Reports - Filters", "Filter unsuccessful outcomes by one or more respondents.", ADMIN_ROLES),
    ("termination_reasons.filter.status", "Filter by status", "Term Reports - Filters", "Filter outcomes by terminated, quota or quality/security status.", ADMIN_ROLES),
    ("termination_reasons.filter.country", "Filter by country", "Term Reports - Filters", "Filter unsuccessful outcomes by one or more survey countries.", ADMIN_ROLES),
    ("termination_reasons.filter.client", "Filter by client", "Term Reports - Filters", "Filter provider outcomes by client integration.", ADMIN_ROLES),
    ("termination_reasons.filter.buyer", "Filter by buyer ID", "Term Reports - Filters", "Filter provider outcomes by one or more buyer or sub-client IDs.", ADMIN_ROLES),
    ("termination_reasons.filter.date", "Filter by date and time", "Term Reports - Filters", "Filter by an IST start or end date-time range.", ADMIN_ROLES),
    ("termination_reasons.filters.clear", "Clear outcome filters", "Term Reports - Filters", "Clear all Term Reports list filters.", ADMIN_ROLES),
    ("termination_reasons.export", "Export Term Reports Excel", "Term Reports - Actions", "Download the filtered report as Excel with both platform and provider statuses.", ADMIN_ROLES),
    ("termination_reasons.card.total", "Show Unsuccessful card", "Term Reports - Summary cards", "Display total unsuccessful outcomes.", ADMIN_ROLES),
    ("termination_reasons.card.terminated", "Show Terminated card", "Term Reports - Summary cards", "Display terminated outcomes.", ADMIN_ROLES),
    ("termination_reasons.card.quota", "Show Quota full card", "Term Reports - Summary cards", "Display quota-full outcomes.", ADMIN_ROLES),
    ("termination_reasons.card.quality", "Show Quality / security card", "Term Reports - Summary cards", "Display quality and security outcomes.", ADMIN_ROLES),
    ("termination_reasons.control.pagination", "Use outcome pagination", "Term Reports - Page controls", "Move between pages of unsuccessful respondent outcomes.", ADMIN_ROLES),
    ("termination_reasons.action.details", "Open outcome details", "Term Reports - Actions", "Open an individual RID's full provider outcome modal.", ADMIN_ROLES),
    ("termination_reasons.action.refresh", "Refresh provider outcome", "Term Reports - Actions", "Fetch and cache the latest transaction status and term reason from the survey provider.", ADMIN_ROLES),
    ("termination_reasons.column.rid", "Show RID column", "Term Reports - Table columns", "Display the respondent RID.", ADMIN_ROLES),
    ("termination_reasons.column.survey", "Show survey column", "Term Reports - Table columns", "Display project and survey identifiers.", ADMIN_ROLES),
    ("termination_reasons.column.client", "Show client column", "Term Reports - Table columns", "Display client and provider identity.", ADMIN_ROLES),
    ("termination_reasons.column.respondent", "Show respondent column", "Term Reports - Table columns", "Display the associated platform user.", ADMIN_ROLES),
    ("termination_reasons.column.status", "Show status column", "Term Reports - Table columns", "Display normalized final status.", ADMIN_ROLES),
    ("termination_reasons.column.ended", "Show ended column", "Term Reports - Table columns", "Display callback or final activity time.", ADMIN_ROLES),
    ("termination_reasons.column.actions", "Show detail action column", "Term Reports - Table columns", "Display the individual outcome Details action.", ADMIN_ROLES),
    ("termination_reasons.field.status", "Show status details", "Term Reports - Result fields", "Display normalized and provider-reported statuses.", ADMIN_ROLES),
    ("termination_reasons.field.reason", "Show term reason", "Term Reports - Result fields", "Display the exact provider term reason and category metadata.", ADMIN_ROLES),
    ("termination_reasons.field.respondent", "Show respondent details", "Term Reports - Result fields", "Display respondent RID, user and captured network address.", ADMIN_ROLES),
    ("termination_reasons.field.survey", "Show survey details", "Term Reports - Result fields", "Display project, survey, client and provider identifiers.", ADMIN_ROLES),
    ("termination_reasons.field.timing", "Show timing details", "Term Reports - Result fields", "Display start, callback and recorded LOI details.", ADMIN_ROLES),
    ("termination_reasons.field.audit", "Show audit details", "Term Reports - Result fields", "Display callback source, verification and provider lookup time.", ADMIN_ROLES),

    ("user_hits.view", "View User Hits page, sidebar and rows", "User Hits - Page & navigation", "Open User Hits, display its sidebar item and read aggregated user rows through the API.", TRACKING_ROLES),
    ("user_hits.filter.search", "Use Search filter", "User Hits - Filters", "Search users, email addresses, branches and sub-branches.", TRACKING_ROLES),
    ("user_hits.filter.branch", "Use Branch filter", "User Hits - Filters", "Filter User Hits by one or more branches.", TRACKING_ROLES),
    ("user_hits.filter.sub_branch", "Use Sub-branch filter", "User Hits - Filters", "Filter User Hits by one or more sub-branches.", TRACKING_ROLES),
    ("user_hits.filter.shift", "Use Shift filter", "User Hits - Filters", "Filter User Hits by one or more shifts.", TRACKING_ROLES),
    ("user_hits.filter.user", "Use User filter", "User Hits - Filters", "Filter User Hits by one or more users.", TRACKING_ROLES),
    ("user_hits.filter.date", "Use Date and time filter", "User Hits - Filters", "Filter entry timestamps with combined From and To controls.", TRACKING_ROLES),
    ("user_hits.filters.clear", "Clear User Hits filters", "User Hits - Filters", "Use the Clear filters action on User Hits.", TRACKING_ROLES),
    ("user_hits.card.total_hits", "Show Total hits card", "User Hits - Summary cards", "Display filtered hit totals.", TRACKING_ROLES),
    ("user_hits.card.completes", "Show Completes card", "User Hits - Summary cards", "Display successful completes.", TRACKING_ROLES),
    ("user_hits.card.conversion", "Show Conversion card", "User Hits - Summary cards", "Display completes divided by hits.", TRACKING_ROLES),
    ("user_hits.card.active_users", "Show Active users card", "User Hits - Summary cards", "Display users matching current filters.", TRACKING_ROLES),
    ("user_hits.card.devices", "Show Completed devices card", "User Hits - Summary cards", "Display completed Desktop, Mobile and Tablet journeys.", TRACKING_ROLES),
    ("user_hits.card.ir", "Show IR card", "User Hits - Summary cards", "Display completes divided by completes plus actual survey terminations.", TRACKING_ROLES),
    ("user_hits.control.page_size", "Change rows per page", "User Hits - Page controls", "Change the number of user-hit rows displayed per page.", TRACKING_ROLES),
    ("user_hits.control.pagination", "Use pagination", "User Hits - Page controls", "Move between pages of user-hit rows.", TRACKING_ROLES),
    ("user_hits.column.branch", "Show Branch column", "User Hits - Table columns", "Display the user's branch.", TRACKING_ROLES),
    ("user_hits.column.sub_branch", "Show Sub-branch column", "User Hits - Table columns", "Display the user's sub-branch.", TRACKING_ROLES),
    ("user_hits.column.shift", "Show Shift column", "User Hits - Table columns", "Display the user's assigned shift.", TRACKING_ROLES),
    ("user_hits.column.user", "Show User column", "User Hits - Table columns", "Display user identity details.", TRACKING_ROLES),
    ("user_hits.column.date", "Show Date column", "User Hits - Table columns", "Display the IST calendar date.", TRACKING_ROLES),
    ("user_hits.column.hits", "Show Hits column", "User Hits - Table columns", "Display total and device-wise hits.", TRACKING_ROLES),
    ("user_hits.column.completes", "Show Completes column", "User Hits - Table columns", "Display total and device-wise completes.", TRACKING_ROLES),

    ("organization.view", "View Organization page and hierarchy", "Organization - Page & navigation", "Open Organization and read the permitted Branch, Sub-branch and Shift tree.", ADMIN_ROLES),
    ("organization.card.branches", "Show Branches card", "Organization - Summary cards", "Display active organization branches.", ADMIN_ROLES),
    ("organization.card.shifts", "Show Shifts card", "Organization - Summary cards", "Display active organization shifts.", ADMIN_ROLES),
    ("organization.card.members", "Show Members card", "Organization - Summary cards", "Display assigned organization members.", ADMIN_ROLES),
    ("organization.card.client_grants", "Show Client grants card", "Organization - Summary cards", "Display active hierarchy client grants.", ADMIN_ROLES),
    ("organization.tab.structure", "View Structure tab", "Organization - Tabs", "Display Branch, Sub-branch and Shift hierarchy.", ADMIN_ROLES),
    ("organization.tab.client_access", "View Client access tab", "Organization - Tabs", "Display client visibility assignments for hierarchy units.", ADMIN_ROLES),
    ("organization.tab.clients", "View Client catalog tab", "Organization - Tabs", "Display the platform client catalog.", ("super-admin",)),
    ("organization.manage", "Manage organization units", "Organization - Actions", "Create, edit and deactivate Branch, Sub-branch and Shift units.", ADMIN_ROLES),
    ("organization.clients.manage", "Manage unit client access", "Organization - Actions", "Assign eligible clients to Branch, Sub-branch or Shift units.", ADMIN_ROLES),
    ("organization.action.create_unit", "Create organization unit", "Organization - Actions", "Open and submit the Branch, Sub-branch or Shift creation modal.", ADMIN_ROLES),
    ("organization.action.edit_unit", "Edit organization unit", "Organization - Actions", "Edit or deactivate an organization unit.", ADMIN_ROLES),
    ("organization.action.delete_unit", "Delete organization unit", "Organization - Actions", "Permanently delete an unused Branch, Sub-branch or Shift after confirmation.", ADMIN_ROLES),
    ("organization.action.assign_client", "Assign unit client", "Organization - Actions", "Create or edit a unit-level client visibility grant.", ADMIN_ROLES),
    ("organization.action.remove_client", "Remove unit client access", "Organization - Actions", "Permanently remove a client visibility grant from a Branch, Sub-branch or Shift.", ADMIN_ROLES),
    ("organization.column.unit.path", "Show Unit path column", "Organization - Structure columns", "Display the full Branch / Sub-branch / Shift path.", ADMIN_ROLES),
    ("organization.column.unit.type", "Show Unit type column", "Organization - Structure columns", "Display the hierarchy level.", ADMIN_ROLES),
    ("organization.column.unit.members", "Show Members column", "Organization - Structure columns", "Display assigned user totals.", ADMIN_ROLES),
    ("organization.column.unit.clients", "Show Clients column", "Organization - Structure columns", "Display direct client grant totals.", ADMIN_ROLES),
    ("organization.column.unit.status", "Show Unit status column", "Organization - Structure columns", "Display active or inactive state.", ADMIN_ROLES),
    ("organization.column.unit.actions", "Show Unit actions column", "Organization - Structure columns", "Display unit editing actions.", ADMIN_ROLES),
    ("organization.column.access.unit", "Show Client-access unit column", "Organization - Client access columns", "Display the assigned organization unit.", ADMIN_ROLES),
    ("organization.column.access.client", "Show Client-access client column", "Organization - Client access columns", "Display the visible client.", ADMIN_ROLES),
    ("organization.column.access.cpi", "Show Client-access CPI range", "Organization - Client access columns", "Display inherited minimum and maximum source CPI policy.", ADMIN_ROLES),
    ("organization.column.access.status", "Show Client-access status column", "Organization - Client access columns", "Display client-grant state.", ADMIN_ROLES),
    ("organization.column.access.actions", "Show Client-access actions column", "Organization - Client access columns", "Display client-grant editing actions.", ADMIN_ROLES),

    ("sync.view", "View synchronization history", "Synchronization", "View inventory synchronization runs.", ("manager", "admin", "super-admin")),
    ("sync.run", "Run synchronization", "Projects - Actions", "Manually trigger an inventory synchronization.", ADMIN_ROLES),
    ("permissions.view", "View permission catalog", "Access control", "View functions that may be delegated.", TRACKING_ROLES),
    ("roles.view", "View roles", "Access control", "View roles available within the user's scope.", TRACKING_ROLES),
    ("roles.create", "Create subordinate roles", "Access control", "Create roles from grantable functions.", ADMIN_ROLES),
    ("roles.update", "Update owned roles", "Access control", "Update roles created by the current user.", ADMIN_ROLES),
    ("roles.delete", "Delete owned roles", "Access control", "Delete unused roles created by the current user.", ADMIN_ROLES),
    ("users.view", "View subordinate users", "Access control", "View users created below the current account.", TRACKING_ROLES),
    ("users.create", "Create subordinate users", "Access control", "Create permitted subordinate accounts.", ("manager", "admin", "super-admin")),
    ("users.update", "Update subordinate users", "Access control", "Update roles and individual overrides.", ("manager", "admin", "super-admin")),
    ("users.delete", "Delete subordinate users", "Access control", "Delete permitted subordinate accounts.", ADMIN_ROLES),
    ("users.manage", "Manage employees", "Access control", "Legacy employee-management access.", ADMIN_ROLES),
    ("access.manage", "Manage roles and permissions", "Access control", "Configure functions, roles and user overrides.", ("super-admin",)),
    ("access.cint_email_pool.manage", "Manage Cint respondent emails", "Access control - Sensitive data", "Import real respondent emails into the encrypted Cint identity pool and view aggregate pool status.", ("super-admin",)),
    ("api_docs.view", "View API documentation", "Development", "Open internal Swagger documentation.", ADMIN_ROLES),
    ("clients.view", "View clients", "Supplier Management - Page & navigation", "View client and integration metadata.", ("super-admin",)),
    ("clients.manage", "Manage clients", "Supplier Management - Actions", "Create and update client metadata.", ("super-admin",)),
    ("clients.integration.view", "View client integrations", "Organization - Client integrations", "View non-secret provider connection metadata and status.", ("super-admin",)),
    ("clients.integration.manage", "Create and edit integrations", "Organization - Client integrations", "Create, update, pause or deactivate client integration settings.", ("super-admin",)),
    ("clients.integration.test", "Test integration connection", "Organization - Client integrations", "Run a safe provider authentication test.", ("super-admin",)),
    ("clients.integration.preview", "Preview provider inventory", "Organization - Client integrations", "Fetch a bounded read-only provider inventory preview.", ("super-admin",)),
    ("clients.integration.sync", "Run client integration sync", "Organization - Client integrations", "Queue an immediate provider inventory synchronization.", ("super-admin",)),
    ("vendors.view", "View Supplier Management page and sidebar", "Supplier Management - Page & navigation", "Open Supplier Management and display its sidebar item.", ("super-admin",)),
    ("vendors.manage", "Manage supplier policies", "Supplier Management - Actions", "Configure supplier CPI and delivery policies.", ("super-admin",)),
    ("allocations.view", "View allocations", "Supplier Management - Page & navigation", "View client and project quantity allocations.", ("super-admin",)),
    ("allocations.manage", "Manage allocations", "Supplier Management - Actions", "Create and update client and project caps.", ("super-admin",)),
    ("respondents.create", "Create supplier respondents", "Access control - Actions", "Create respondents below an internal supplier.", ("admin", "super-admin")),
    ("vendors.card.vendors", "Show Suppliers card", "Supplier Management - Summary cards", "Display internal and external supplier totals.", ("super-admin",)),
    ("vendors.card.client_grants", "Show Client grants card", "Supplier Management - Summary cards", "Display active supplier-client grants.", ("super-admin",)),
    ("vendors.card.projects", "Show Allocated projects card", "Supplier Management - Summary cards", "Display project allocation totals.", ("super-admin",)),
    ("vendors.tab.policies", "View Suppliers tab", "Supplier Management - Tabs", "Display the Suppliers commercial-policy tab.", ("super-admin",)),
    ("vendors.tab.clients", "View Client allocations tab", "Supplier Management - Tabs", "Display client allocation records.", ("super-admin",)),
    ("vendors.tab.projects", "View Project allocations tab", "Supplier Management - Tabs", "Display project allocation records.", ("super-admin",)),
    ("vendors.tab.api_keys", "View API keys tab", "Supplier Management - Tabs", "Display external supplier API keys.", ("super-admin",)),
    ("vendors.action.create", "Create supplier", "Supplier Management - Actions", "Open Access Control to create a supplier account.", ("super-admin",)),
    ("vendors.action.edit_policy", "Edit supplier policy", "Supplier Management - Actions", "Create or edit supplier commercial policy records.", ("super-admin",)),
    ("vendors.action.allocate_client", "Allocate client", "Supplier Management - Actions", "Create or edit client allocation records.", ("super-admin",)),
    ("vendors.action.allocate_project", "Allocate project", "Supplier Management - Actions", "Create or edit project allocation records.", ("super-admin",)),
    ("vendors.action.create_api_key", "Generate API key", "Supplier Management - Actions", "Issue a new external supplier API key.", ("super-admin",)),
    ("vendors.action.revoke_api_key", "Revoke API key", "Supplier Management - Actions", "Revoke an external supplier API key.", ("super-admin",)),
    ("vendors.column.vendor.name", "Show Supplier column", "Supplier Management - Supplier columns", "Display supplier identity.", ("super-admin",)),
    ("vendors.column.vendor.type", "Show Type column", "Supplier Management - Supplier columns", "Display internal or external supplier type.", ("super-admin",)),
    ("vendors.column.vendor.cpi", "Show Default CPI column", "Supplier Management - Supplier columns", "Display the supplier CPI policy.", ("super-admin",)),
    ("vendors.column.vendor.clients", "Show Clients column", "Supplier Management - Supplier columns", "Display allocated-client counts.", ("super-admin",)),
    ("vendors.column.vendor.status", "Show Status column", "Supplier Management - Supplier columns", "Display supplier policy status.", ("super-admin",)),
    ("vendors.column.vendor.actions", "Show supplier Actions column", "Supplier Management - Supplier columns", "Display supplier policy row actions.", ("super-admin",)),
    ("vendors.column.client.vendor", "Show Supplier column", "Supplier Management - Client allocation columns", "Display the allocated supplier.", ("super-admin",)),
    ("vendors.column.client.client", "Show Client column", "Supplier Management - Client allocation columns", "Display the allocated client.", ("super-admin",)),
    ("vendors.column.client.cpi", "Show CPI cut column", "Supplier Management - Client allocation columns", "Display the effective client CPI cut.", ("super-admin",)),
    ("vendors.column.client.window", "Show Active window column", "Supplier Management - Client allocation columns", "Display allocation start and end timestamps.", ("super-admin",)),
    ("vendors.column.client.actions", "Show client Actions column", "Supplier Management - Client allocation columns", "Display client allocation row actions.", ("super-admin",)),
    ("vendors.column.project.vendor", "Show Supplier column", "Supplier Management - Project allocation columns", "Display the project supplier.", ("super-admin",)),
    ("vendors.column.project.survey", "Show Survey column", "Supplier Management - Project allocation columns", "Display project and survey identifiers.", ("super-admin",)),
    ("vendors.column.project.client", "Show Client column", "Supplier Management - Project allocation columns", "Display the project client.", ("super-admin",)),
    ("vendors.column.project.cpi", "Show CPI cut column", "Supplier Management - Project allocation columns", "Display the effective project CPI cut.", ("super-admin",)),
    ("vendors.column.project.actions", "Show project Actions column", "Supplier Management - Project allocation columns", "Display project allocation row actions.", ("super-admin",)),
    ("vendors.column.api.vendor", "Show Supplier column", "Supplier Management - API key columns", "Display the API-key owner.", ("super-admin",)),
    ("vendors.column.api.key", "Show Key column", "Supplier Management - API key columns", "Display masked API-key metadata.", ("super-admin",)),
    ("vendors.column.api.created", "Show Created column", "Supplier Management - API key columns", "Display API-key creation time.", ("super-admin",)),
    ("vendors.column.api.last_used", "Show Last used column", "Supplier Management - API key columns", "Display the last API-key use time.", ("super-admin",)),
    ("vendors.column.api.expires", "Show Expires column", "Supplier Management - API key columns", "Display API-key expiration time.", ("super-admin",)),
    ("vendors.column.api.actions", "Show API-key Actions column", "Supplier Management - API key columns", "Display API-key revoke actions.", ("super-admin",)),
)


@transaction.atomic
def sync_access_function_catalog(**_kwargs):
    """Synchronize code-defined functions without resetting configured access."""

    from .models import AccessFunction, Role, RoleFunctionPermission

    for code, name, module, description, default_roles in FUNCTION_CATALOG:
        function, created = AccessFunction.objects.update_or_create(
            code=code,
            defaults={"name": name, "module": module, "description": description, "is_active": True},
        )
        if not created:
            continue
        for role in Role.objects.filter(slug__in=default_roles, is_active=True):
            RoleFunctionPermission.objects.get_or_create(
                role=role,
                function=function,
                defaults={"allowed": True},
            )
