# Generated by Django 5.2.5 on 2026-08-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_clientintegration_profile_reuse_first_delay_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorclientallocation',
            name='client_consumed_not_above_limit',
        ),
        migrations.RemoveConstraint(
            model_name='vendorclientallocation',
            name='client_reserved_within_remaining',
        ),
        migrations.RemoveConstraint(
            model_name='vendorsurveyallocation',
            name='survey_consumed_not_above_limit',
        ),
        migrations.RemoveConstraint(
            model_name='vendorsurveyallocation',
            name='survey_reserved_within_remaining',
        ),
        migrations.RemoveField(
            model_name='allocationreservation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='vendorclientallocation',
            name='consumed_quantity',
        ),
        migrations.RemoveField(
            model_name='vendorclientallocation',
            name='quantity_limit',
        ),
        migrations.RemoveField(
            model_name='vendorclientallocation',
            name='reserved_quantity',
        ),
        migrations.RemoveField(
            model_name='vendorsurveyallocation',
            name='consumed_quantity',
        ),
        migrations.RemoveField(
            model_name='vendorsurveyallocation',
            name='quantity_limit',
        ),
        migrations.RemoveField(
            model_name='vendorsurveyallocation',
            name='reserved_quantity',
        ),
        migrations.AlterField(
            model_name='vendorapikey',
            name='prefix',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='completed_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='quality_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='quota_full_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='redirect_hash_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='redirect_hash_last_four',
            field=models.CharField(blank=True, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='redirect_hash_prefix',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='redirect_hash_required',
            field=models.BooleanField(default=False, help_text="Require the supplier's separately generated hash key on respondent entry links."),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='survey_id_mode',
            field=models.CharField(choices=[('project_id', 'Project ID'), ('source_id', 'Upstream survey ID')], default='project_id', help_text="Identifier exposed as survey_id/source_id in this key's survey feed.", max_length=20),
        ),
        migrations.AddField(
            model_name='vendorapikey',
            name='terminated_redirect_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
